### ISSUE TITLE
Fungerende søk i Altinn innboks – (kobles/trackes av Roadmap-element) - [Kan beskrives som funksjon / egenskap eller som overordnet brukerhistorie]

### ISSUE THREAD

**Issue by krteige** [Altinn/dialogporten-frontend#1380]
```[tasklist]
### (User) Stories
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1379
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1374
- [ ] Brukerhistorie: Som dyslektiker ønsker jeg at søkefunksjonen forstår feilstavelser, deler av ord og synonymer, slik at jeg lettere  og effektivt får tilgang til relevant informasjon
- [ ] Brukerhistorier Som proffbruker med tilgang til mange aktører og innbokser, vil jeg kunne søke i aktørvalglisten for å raskere finne aktøren / innboksen jeg leter etter
```

```[tasklist]
### Hypoteser – kan de ligge her?
- [ ] Ved å gi brukeren mulighet til markere favoritter og prioritere aktørvalgene, vil brukeren enklere få tilgang til sine mest brukte aktører / innbokser
- [ ] Hypotese Ved å gi proffbrukere – som håndterer 200 innbokser / aktører – muligheten til å søke i aktørlisten, vil brukeren raskere finne aktøren og velge innboksen de leter etter.
```

**Comment by krteige** [comment]
Denne ble laget som eksempel på ny Github-struktur og Epic. Har ingenting med faktiske arbeidsoppgaver å gjøre.
