### ISSUE TITLE
Fungerende filter i Innboks – (kobles/trackes av Roadmap-element) – [Kan beskrives som funksjon / egenskap eller som overordnet brukerhistorie]

### ISSUE THREAD

**Issue by krteige** [Altinn/dialogporten-frontend#1401]
```[tasklist]
### (User) stories
- [ ] Brukerhistorier Som en bruker ønsker jeg å enkelt kunne filtrere meldinger i innboksen basert på tilgjengelige statuser, slik at jeg raskt kan filtrere meg ned på et spesifikke brukerbehov
- [ ] Brukerhistorier Som en proffbruker med stor og komplisert innboks, ønsker jeg at filtrering av innhold skal være lettere og mer tilgjengelig, slik at jeg enkelt kan finne relevant informasjon
- [ ] Brukerhistorier Som bruker ønsker jeg  flere tidssorteringsfunksjoner (som ukens. månedens, datovelger o.l.) i innboksen
```

```[tasklist]
### Hypoteser (kan de ligge her?)
- [ ] Hypotese 1
- [ ] Hypotese 2
```

**Comment by krteige** [comment]
Ble brukt for å lage eksempel til ny Github-struktur. Har ingenting med faktiske arbeidsoppgaver å gjøre.
