### ISSUE TITLE
For verifisering av Dialoger må SKD sin bruk av Transmissions hensyntas

### ISSUE THREAD

**Issue by LeifHelstad** [Altinn/dialogporten-frontend#1447]
```[tasklist]
### Hypoteser
- [x] SKD har sin forventning til hva fra transmissions som vises i dialogen i arbeidsflate. Digdir og SKD sin implementasjon og forventning må harmoniseres.
- [x] Skatt sin innbox (MinDialog) kommer ikke til å gå direkte på Dialogportens som EndUser. All oppdatering av dialoger vil skje via skatt sitt baksystem DialogBox og da alltid som ServiceOwner.
```

Det vil være nødvendig å implementere #871 for å kunne påbegynne analyse av samsvar mellom forventning og visning av innhold fra transmission.

```[tasklist]
### Tasks
- [x] Test må i samarbeid mellom Digdir og SKD analysere de faktiske resultater fra UAT for å eventuelt avdekke avvik i forventning.
- [x] Avklare med SKD om deres intensjon ved bruk av Related Transmission
```

**Comment by LeifHelstad** [comment]
**Spørsmål til skatt 9/12-24:**
Et oppfølgingsspørsmål basert på dialogen 01932f54-0f01-71fe-a94d-8e017089f822
Den innholder to transmissions
"id": "01932f54-0f95-7edd-82f3-10e4db578ae1"
"id": "01932f56-df19-7a35-9bcc-30bd2464d7bf"
Der den siste inneholder en peker tilbake til den første slik at de danner en tråd.
"relatedTransmissionId": "01932f54-0f95-7edd-82f3-10e4db578ae1"
 
Spørsmålet mitt er da:
Kommer dere til å ha en kun en eller kommer dere til å ha flere "topp" transmissions (som ikke refererer andre) per dialog?

**Comment by LeifHelstad** [comment]
## Til diskusjon
* Hvordan transmissions henger på en dialog og på hverandre er mer et dialogporten spørsmål enn et arbeidsflate spørsmål. Bør denne saken bytte repo?
* Forholder design seg til repo dialogporten? Eller er det god grunn for å holde denne i repo dialogporten-frontens fordi dette i stor grad er et designspørsmål hvordan transmissions og activities skal forholde seg til hverandre?

**Comment by LeifHelstad** [comment]
## Info fra SKE
**Reglene for tilbakemeldingene i GLD:**

- Hvis oppgavegiver og innsender er like og GLD klarer å behandle leveranse så sender GLD kun 1 tilbakemelding (leveransetilbakemelding)
- Hvis oppgavegiver og innsender er like og GLD ikke klarer å behandle (lese inn) leveranse så sender GLD kun 1 tilbakemelding (innsendingtilbakemelding)
- Hvis oppgavegiver !og innsender er ulike og GLD klarer å behandle leveranse så sender GLD 2 tilbakemeldinger (innsendingstilbakemelding til innsender og leveransetilbakemelding til oppgavegiver)
- Hvis oppgavegiver og innsender er ulike og GLD ikke klarer å behandle (lese inn) leveranse så sender GLD kun 1 tilbakemelding (innsendingstilbakemelding til innsender)

En leveransetilbakemelding kan inneholde flere filer (det sendes minst 2 filer, en pdf og en xml fil og i tillegg kan vi sende en csv fil med alle avvik).
En innsendingtilbakemelding kan også inneholde flere filer (det sendes minst 2 filer, en pdf og en xml fil og i tillegg kan vi sende en zip fil med alle leveransetilbakemeldingene).
Kommentar: Husk at for tasteskjema er det kun gjeldene når Innsender er lik oppgavegiver. Men for M2M kan det være forskjellige. OBS! Automatiske tilbakemeldinger genereres kun for gjeldende inntektsår (f.eks 2024), hvis du sender for et tidligere inntektsår f.eks 2023 så må innsending godkjennes manuelt for å trigge utsending av tilbakemelding.

**Comment by LeifHelstad** [comment]
## Konklusjon

### Eksempelet
Diskusjonen med skatt gikk på flere typer innrapporterig, men boligselskap ble valgt som et ekspempel fra skatt fordi det er et typisk tilfelle der oppgavegiver og innsender er og ikke er den samme.
(For kompletthet og ikke noe annet: https://skatteetaten.github.io/api-dokumentasjon/api/innrapportering-boligselskap)

### Funn
Det er ikke gjort noen funn som bryter med det som allerede gjøres og som i skrivende stund er oppfattet skal skje med transmissons. (GLD er Skatt sin tjeneste for behandling av grunnlagsdata)

Likevel, her en "oversettelse" av "tilbakemelding" i Skatt sine kulepunkter til "dialoger" og "transmissions" i dialogporten.

- Hvis oppgavegiver og innsender er like og GLD klarer å behandle leveranse:
   - En dialog med en transmission for "suksess" og en transmission for "innhold" 

- Hvis oppgavegiver og innsender er like og GLD ikke klarer å behandle (lese inn) leveranse
   - En dialog med en transmission for "mislykket"

- Hvis oppgavegiver !og innsender er ulike og GLD klarer å behandle leveranse
   - En dialog til "innsender" med en transmission for "suksess"
   - En dialog til "oppgavegiver" med en transmission for "innhold"

- Hvis oppgavegiver og innsender er ulike og GLD ikke klarer å behandle (lese inn) leveranse
   - En dialog til "innsender" med en transmission for "mislykket"

### Oppsummering
Denne Storyen har vært i "forskningsmodus" en stund. Dagens funn viser at det ikke er grunnlag for noen særbehandling.
Den bør likevel få sin endelige lukking av PO eller relevant representant. @MetteSaltnes || @knuthalvor

**Comment by LeifHelstad** [comment]
Lukker etter å ha presentert samsvar i transmissions for Mette.
