### ISSUE TITLE
Arbeidsflate skal benytte felles komponenter for felles funksjoner

### ISSUE THREAD

**Issue by LeifHelstad** [Altinn/dialogporten-frontend#1566]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1497
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1499
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1500
```

**Comment by knuthalvor** [comment]
@LeifHelstad @MetteSaltnes: vil tro denne kanskje kan lukkes, eller er det noe annet konkret som skal utføres på denne?

**Comment by LeifHelstad** [comment]
De issues som er nevnt konkret er lukket for en stund siden.
Men helt reelt er det å ta i bruk komponetet fra altinn-componets over hele arbeidsfalten noe som ikke ble leverte i stort monn før i forrige uke. Der har jeg testet en del, det ser OK ut. Derfor kan jeg lukke denne helt generelle her som samtidig har et mer teknisk enn funksjonelt preg.
