### ISSUE TITLE
Improving dialogs

### ISSUE THREAD

**Issue by ingefossland** [Altinn/dialogporten-frontend#305]
## Problem

Improving 

```[tasklist]
### Issues and hypothesis
- [ ] https://github.com/digdir/dialogporten-frontend/issues/377
- [ ] https://github.com/digdir/dialogporten-frontend/issues/374
- [ ] https://github.com/digdir/dialogporten-frontend/issues/376
- [ ] https://github.com/digdir/dialogporten-frontend/issues/408
- [ ] Users need to understand if a dialog contains an important task
- [ ] https://github.com/digdir/dialogporten-frontend/issues/449
```

```[tasklist]
### Explorations and design
- [ ] https://github.com/digdir/dialogporten-frontend/issues/378
- [ ] https://github.com/digdir/dialogporten-frontend/issues/379
- [ ] Konceptrunde 1
- [ ] Konseptrunde 2
```
