### ISSUE TITLE
Implement ID-porten authentication and session handling

### ISSUE THREAD

**Issue by elsand** [Altinn/dialogporten-frontend#55]
## Description
Implement authentication with ID-porten in arbeidsflate.

## Additional Information

The session table will have to contain
* sessionId (vår egen genererte sesjonsid - må være ugjettbar og unik)
* createdTimestamp (når sesjonen ble oppretta)
* idportenSessionId (sid fra id_token, som vi bruker for single logout)
* pid (fnr som vi bruker som fremmednøkkel til bruker/profil-tabell)
* accessToken (fra idporten som brukes mot Dialogporten)
* accessTokenExpires (tidspunkt for når accessToken expirer (og nytt må hentes fra idporten med refreshtoken))
* refreshToken (fra idporten som brukes for å hente nytt accessToken)
* refreshTokenExpires (tidspunkt for når refreshTokenExpires)
* sessionData (andre data relevant for sesjonen, f.eks. hvilken URL var det brukeren forsøkte å aksessere uten autentisering, som vi da kan redirecte til etter innlogging)

## Tasks

```[tasklist]
- [x] Sette opp klient i samarbeidsportalen
- [x] Finne bibliotek for Node
- [x] Implementert innlogging og mottak av tokens
- [ ] Etablere lagring av sesjonsdata i en backed
- [ ] Håndtere utlogging fra arbeidsflate (post til idporten/logout)
- [ ] Håndtere single-logout via ID-porten initiert fra annet sted (definere front_channel_logout_uri)
- [ ] Etablere sesjonshåndtering basert på sesjonscookie
```

**Comment by AudunFK** [comment]
Lukkes etter avtale med Bjørn.
