### ISSUE TITLE
Skeleton for å indikere lasting av data

### ISSUE THREAD

**Issue by seanes** [Altinn/dialogporten-frontend#672]
### Description

Mens vi henter data bør vi vise en loader (skeleton feks. for visningselementer dersom den ikke har gamle?).
Et interessant spor er å se på https://storybook.designsystemet.no/?path=/docs/komponenter-loaders-skeleton--docs

Det er blitt foreslått https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-UI-%E2%80%93-del-A?node-id=268-30947&t=Ci8UamrN5Fq91p1R-4 - den tekniske utfordringen som gjør at det ikke kan realiseres, er at vi henter og får alle dialogene samtidig.

```[tasklist]
### Tasks
- [x] Skeleton for søk
- [x] Skeleton for Inbox
- [x] SKeleton for søke dropdown
- [ ] https://github.com/digdir/dialogporten-frontend/pull/727
```
