### ISSUE TITLE
Frontend Setup

### ISSUE THREAD

**Issue by alexdigdir** [Altinn/dialogporten-frontend#72]

**Comment by alexdigdir** [comment]
- [x] [Dialogporten: Basic setup with needed deps: yarn, typescript, react og webpack. | altinn-studio#11054](https://github.com/Altinn/altinn-studio/issues/11054)
- [x] [Dialogporten: Ensure to enable strict-null-check in tsconfig.json | altinn-studio#11064](https://github.com/Altinn/altinn-studio/issues/11064)
- [ ] [Dialogporten: Add README.md to the project | altinn-studio#11070](https://github.com/Altinn/altinn-studio/issues/11070)
- [ ] [Dialogporten: Prettier and Linting | altinn-studio#11063](https://github.com/Altinn/altinn-studio/issues/11063)
- [ ] [Dialogporten: Setup for unit-testing | altinn-studio#11055](https://github.com/Altinn/altinn-studio/issues/11055)
- [ ] [Dialogporten: Run tests, prettier, lint and typecheck in pipeline | altinn-studio#11062](https://github.com/Altinn/altinn-studio/issues/11062)
- [ ] [Dialogporten: Install React Router to support routes | altinn-studio#11056](https://github.com/Altinn/altinn-studio/issues/11056)
- [ ] [Dialogporten: Install digdir/designsystem package | altinn-studio#11057](https://github.com/Altinn/altinn-studio/issues/11057)
- [ ] [Dialogporten: Login/Session | altinn-studio#11061](https://github.com/Altinn/altinn-studio/issues/11061)
- [ ] [Dialogporten: Install and setup Tanstack Query (React Query) | altinn-studio#11072](https://github.com/Altinn/altinn-studio/issues/11072)
- [ ] [Dialogporten: CI/CD pipelines | altinn-studio#11060](https://github.com/Altinn/altinn-studio/issues/11060)
- [ ] [Implement code coverage report in pipeline/workflow | altinn-studio#11113](https://github.com/Altinn/altinn-studio/issues/11113)

**Comment by nkylstad** [comment]
@alexdigdir The issues referenced here are in the altinn-studio repo. Can they be either moved to this repo or closed?

**Comment by krteige** [comment]
@alexdigdir Kan denne lukkes?

**Comment by alexdigdir** [comment]
Done.
