### ISSUE TITLE
Map Service Blueprints

### ISSUE THREAD

**Issue by ingefossland** [Altinn/dialogporten-frontend#760]
Link to Brreg blueprint:
https://miro.com/app/board/uXjVKhGn_1c=/?moveToWidget=3458764601588973848&cot=14

```[tasklist]
### Tasks
- [x] Consult with Sigurd (and the organization of Digdir) for a blueprint template
- [x] Make Blueprint template
- [x] Map out Blueprint for Skatt / Tredjepartsopplysninger and sync with backend - ongoing
- [x] Initiate collaboration with BRREG on mapping
- [x] Map out Blueprint for Brønnøysundregistrene - registrering av ENK - with designeres
- [x] Draw new sketches based on Brreg mapping
- [x] Map out Blueprint for Brønnøysundregistrene - registrering av ENK  v1 (forsetter)
- [x] Map out Blueprint for Nav – Sykemelding
- [x] Splitte opp Blueprint Sykemelding i mindre brukerreiser med spesielt fokus på painpoints knyttet til historikk
- [x] Map out Blueprint for SSB - innrapportering av ledige stillinger
```
